# AUTOMATICALLY GENERATED
# DO NOT EDIT THIS FILE DIRECTLY. Edit /Dockerfile.erb and run /update instead.

FROM alpine:3.9

RUN apk add --no-cache \
      ca-certificates \
      curl \
      gcc \
      libc-dev \
      make \
      libressl-dev \
      git \
      coreutils \
      gnupg \
      unzip \
      moreutils \
      linux-headers \
      luajit-dev \
      lua5.1-dev \
      lua-turbo \
      luarocks \
  && rm -rf /tmp/lua /tmp/lua.tar.gz \
    && rm -rf /tmp/luarocks /tmp/luarocks.tar.gz \
    && luarocks-5.1 --version \
    && luarocks-5.1 install turbo \
    && luarocks-5.1 install luasocket \
    && luarocks-5.1 install luafilesystem \    
    && luarocks-5.1 install process \
    && luarocks-5.1 install mobdebug \
    && apk del gcc make curl libc-dev lua5.1-dev moreutils coreutils git luarocks \
    && luajit -v
    
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/lib"

WORKDIR /develop/
RUN mkdir db
EXPOSE 8080/tcp 8888/tcp
ENV HC2DOCKER=TRUE


COPY server .
COPY log .
COPY cli .
COPY images/. images/.
COPY dtemplates/. dtemplates/. 
COPY html/. html/.
COPY HC2proxy.lua .
COPY HC2_api.lua .

ENTRYPOINT ["luajit"]
